name: 'telegram_client_linux_example'
description: 'Demonstrates how to use the telegram_client_linux plugin.'
version: '0.0.0'
environment: 
  sdk: '>=3.3.3 <4.0.0'
dependencies: 
  flutter: 
    sdk: 'flutter'
  telegram_client_linux: 
    path: '../'
  cupertino_icons: '^1.0.2'
dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'
  flutter_lints: '^2.0.0'
flutter: 
  uses-material-design: true
publish_to: 'none'
dependency_overrides: 
  pointycastle: '3.8.0'
