name: 'telegram_client_server'
description: 'Telegram Client Lightweight, blazing and Highly customizable for make application telegram based tdlib, mtproto, or bot api and support server side.'
version: '0.8.21'
homepage: 'https://github.com/azkadev/telegram_client'
repository: 'https://github.com/azkadev/telegram_client.git'
issue_tracker: 'https://github.com/azkadev/telegram_client/issues'
documentation: 'https://github.com/azkadev/telegram_client/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '>=3.3.3 <4.0.0'
dev_dependencies: 
  lints: '^2.1.0'
  test: '^1.24.0'
topics: 
  - 'telegram'
  - 'tdlib'
  - 'mtproto'
  - 'userbot'
  - 'bot'
dependency_overrides: 
  pointycastle: '3.8.0'
